#!/usr/bin/env bash
clear

echo "Razer effects
      
      static
      breath_random
		breath_color"

path="/sys/bus/hid/drivers/razerkbd/0003:1532:0209.0004"

echo "Choose your effect"

while :
	do
	read INPUT_STRING
	case $INPUT_STRING in
	static)
		color="$(yad --color | sed -r 's/#//; s/(..)/\\x\1/g')"
		echo -n -e $color > $path/matrix_effect_static
      ;;
   breath_random)
      echo -n "1" > $path/matrix_effect_breath
      ;;
	breath_color)
		echo -n -e $color > $path/matrix_effect_breath
		;;
   exit)
   clear
	exit
      ;;
   *)
      echo "unknow effect"
      ;;
  esac
done
